-- MoP Teleporter By Markus
-- Creature
Delete from creature_template where entry = 900001;
SET @entry := 900001;
SET @display := 29133;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (@entry, 0, 0, 0, 0, 0, @display, 0, 0, 0, 'Teleporter', '', 'Taxi', 62000, 80, 80, 0, 0, 35, 35, 1, 1, 1.14286, 1, 0.2, 0, 0, 0, 0, 0, 1, 2000, 2000, 1, 0, 2048, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 0, 3, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, '', 15595);

-- Gossip_Menu_Option
Delete from gossip_menu_option where menu_id = 62000;
Delete from gossip_menu_option where menu_id = 62001;
Delete from gossip_menu_option where menu_id = 62002;
Delete from gossip_menu_option where menu_id = 62003;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62003, 6, 0, '|TInterface\\icons\\Ability_Marksmanship:30|t<<Back>>', 1, 1, 62000, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62003, 5, 0, '|TInterface\\icons\\Spell_Arcane_PortalShattrath:30|tShattrath', 1, 1, 62003, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62003, 3, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Bloodelf:30|tSilvermoon', 1, 1, 62003, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62003, 2, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Tauren:30|tThunderbluff', 1, 1, 62003, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62003, 1, 0, '|TInterface\\icons\\ability_warlock_baneofhavoc:30|tUndercity', 1, 1, 62003, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62003, 0, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Orc:30|tOrgrimmar', 1, 1, 62003, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62002, 6, 0, '|TInterface\\icons\\Ability_Marksmanship:30|t<<Back>>', 1, 1, 62000, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62002, 5, 0, '|TInterface\\icons\\Spell_Arcane_PortalShattrath:30|tShattrath', 1, 1, 62002, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62002, 3, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Draenei:30|tExodar', 1, 1, 62002, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62002, 2, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Nightelf:30|tDarnassus', 1, 1, 62002, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62002, 1, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Dwarf:30|tIronforge', 1, 1, 62002, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62002, 0, 0, '|TInterface\\icons\\Inv_Misc_Tournaments_banner_Human:30|tStormwind', 1, 1, 62002, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 6, 0, '|TInterface\\icons\\Ability_Marksmanship:30|t<<Back>>', 1, 1, 62000, 0, 0, 0, NULL);
-- INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 5, 0, '|TInterface\\icons\\INV_Misc_Head_Human_02:30|tBarber Shop', 1, 1, 62001, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 4, 0, '|TInterface\\icons\\Ability_Mount_Charger:30|tMounts', 1, 1, 62001, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 3, 0, '|TInterface\\icons\\Ability_Hunter_Pet_GoTo:30|tPets', 1, 1, 62001, 0, 0, 0, NULL);
-- INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 2, 0, '|TInterface\\icons\\INV_BannerPVP_03:30|tArena Overview', 1, 1, 62001, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 1, 0, '|TInterface\\icons\\INV_Misc_Book_16:30|tProfessions', 1, 1, 62001, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62001, 0, 0, '|TInterface\\icons\\INV_Chest_Plate_PVPWarrior_C_02:30|tGear', 1, 1, 62001, 0, 0, 0, NULL);
-- INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 6, 0, '|TInterface\\icons\\Spell_Holy_Mindsooth:30|t[|cff0404B4MALL|r] Custom Shirt Effects', 1, 1, 62000, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 5, 0, '|TInterface\\icons\\Spell_Magic_MageArmor:30|t[|cff0404B4MALL|r] Transmogrification', 1, 1, 62000, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 4, 0, '|TInterface\\icons\\Ability_Warrior_BattleShout:30|t[|cffFF0000FFA|r] Gurubashi Arena', 1, 1, 62000, 0, 0, 0, 'Are You Sure?');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 3, 0, '|TInterface\\icons\\Ability_DualWield:30|t[|cffFF0000PVP|r] Duel Zone', 1, 1, 62000, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 2, 0, '|TInterface\\icons\\Spell_Arcane_PortalTolBarad:30|t[|cff0404B4MALL|r] Shortcuts & Mounts', 1, 1, 62001, 0, 0, 0, NULL);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 1, 0, '|TInterface\\icons\\Ability_TownWatch:30|tMain Cities', 1, 1, 62003, 0, 0, 0, '');
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (62000, 0, 0, '|TInterface\\icons\\Ability_TownWatch:30|tMain Cities', 1, 1, 62002, 0, 0, 0, '');

-- Smart_script
Delete from smart_scripts where entryorguid = 900001;
SET @entry := 900001;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 0, 0, 62, 0, 100, 0, 62001, 0, 0, 0, 62, 870, 0, 0, 0, 0, 0, 7, 0, 0, 0, 838.059, 2008.36, 316.075, 3.30345, 'Gear');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 1, 0, 62, 0, 100, 0, 62001, 1, 0, 0, 62, 870, 0, 0, 0, 0, 0, 7, 0, 0, 0, 843.588, 1982.92, 316.074, 5.81279, 'Professions');
-- INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 2, 0, 62, 0, 100, 0, 62001, 2, 0, 0, 62, 571, 0, 0, 0, 0, 0, 7, 0, 0, 0, 5893.96, 646.667, 645.523, 2.64621, 'Arena Area');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 3, 0, 62, 0, 100, 0, 62001, 3, 0, 0, 62, 870, 0, 0, 0, 0, 0, 7, 0, 0, 0, 796.834, 2030.43, 316.074, 1.15538, 'Pets');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 4, 0, 62, 0, 100, 0, 62001, 4, 0, 0, 62, 870, 0, 0, 0, 0, 0, 7, 0, 0, 0, 796.834, 2056.55, 316.074, 1.9701, 'Mounts');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 5, 0, 62, 0, 100, 0, 62000, 3, 0, 0, 62, 571, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7361.3, -3060.82, 837.47, 5.39, 'Duel Zone');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 6, 0, 62, 0, 100, 0, 62000, 4, 0, 0, 62, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, -13249.6, 191.31, 31.03, 1.12, 'Gurubashi Arena');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 7, 0, 62, 0, 100, 0, 62000, 5, 0, 0, 62, 870, 0, 0, 0, 0, 0, 7, 0, 0, 0, 835.883, 2031.92, 316.074, 0.82344, 'Transmogrification Mall');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 8, 0, 62, 0, 100, 0, 62000, 4, 0, 0, 75, 41367, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Gurubashi Arena Bubble');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 9, 0, 62, 0, 100, 0, 62002, 0, 0, 0, 62, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, -8834.85, 620.938, 93.6702, 0.665581, 'Stormwind');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 10, 0, 62, 0, 100, 0, 62002, 1, 0, 0, 62, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, -4919.95, -956.538, 501.506, 5.39992, 'Ironforge');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 11, 0, 62, 0, 100, 0, 62002, 2, 0, 0, 62, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 9952, 2280.36, 1341.39, 1.58016, 'Darnassus');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 12, 0, 62, 0, 100, 0, 62002, 3, 0, 0, 62, 530, 0, 0, 0, 0, 0, 7, 0, 0, 0, -3958.39, -11747.4, -136.053, 1.07597, 'Exodar');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 13, 0, 62, 0, 100, 0, 62002, 4, 62003, 4, 62, 571, 0, 0, 0, 0, 0, 7, 0, 0, 0, 5794.72, 627.18, 647.393, 0.889945, 'Dalaran');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 14, 0, 62, 0, 100, 0, 62002, 5, 0, 0, 62, 530, 0, 0, 0, 0, 0, 7, 0, 0, 0, -1846.04, 5395.94, -12.428, 2.04199, 'Shattrah');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 15, 0, 62, 0, 100, 0, 62003, 0, 0, 0, 62, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 1562.37, -4402.28, 16.8346, 0.259027, 'Orgrimmar');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 16, 0, 62, 0, 100, 0, 62003, 1, 0, 0, 62, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 1561.65, 240.597, -43.133, 3.10485, 'Undercity');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 17, 0, 62, 0, 100, 0, 62003, 2, 0, 0, 62, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, -1277.37, 124.804, 131.287, 5.22274, 'Thunderbluff');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 18, 0, 62, 0, 100, 0, 62003, 3, 0, 0, 62, 530, 0, 0, 0, 0, 0, 7, 0, 0, 0, 9487.69, -7279.2, 14.2866, 6.14648, 'Silvermoon');
-- INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 19, 0, 62, 0, 100, 0, 62001, 5, 0, 0, 62, 571, 0, 0, 0, 0, 0, 7, 0, 0, 0, 5900.33, 611.42, 650.498, 0.886968, 'BarberShop');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 20, 0, 62, 0, 100, 0, 62003, 5, 0, 0, 62, 530, 0, 0, 0, 0, 0, 7, 0, 0, 0, -1846.04, 5395.94, -12.428, 2.04199, 'Shattrah');
-- INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (@entry, 0, 21, 0, 62, 0, 100, 0, 62000, 6, 0, 0, 62, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, -1596.83, 2543.23, 130.219, 0.687251, 'Custom Shirt Effect Mall');

-- Conditions
SET @id := 62000;
Delete from conditions where SourceTypeOrReferenceId = 15 AND SourceGroup = @id;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (15, 62000, 1, 0, 0, 6, 0, 67, 0, 0, 0, 0, '', 'Teleporter Horde Cities');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (15, @id, 0, 0, 0, 6, 0, 469, 0, 0, 0, 0, '', 'Teleporter Alliance Cities');